[
  {
    planId: null,
    masterPlanId: "6657e5d8c7798c4e40b69ce6",
    name: "Handbook only",
    description: null,
    isCustom: false,
    freeTrialAllowed: true,
    companySize: "Handbook only",
    benefits: [
      {
        benefit: "Unlimited Licenses",
        benefitKey: "benefit-1",
        requiredPayment: false,
        isSame: true,
      },
      {
        benefit: "Unlimited Business Licenses",
        benefitKey: "benefit-10",
        requiredPayment: false,
        isSame: true,
      },
      {
        benefit: "Unlimited Handbooks",
        benefitKey: "benefit-6",
        requiredPayment: false,
        isSame: true,
      },
    ],
    benefitsTrial: [
      {
        benefit: "Unlimited Licenses",
        benefitKey: "benefit-1",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit: "Unlimited Business Licenses",
        benefitKey: "benefit-10",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit: "Unlimited Contact an HR expert",
        benefitKey: "benefit-7",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit: "Unlimited Handbooks",
        benefitKey: "benefit-6",
        requiredPayment: false,
        isSame: false,
      },
    ],
    prices: [
      {
        id: "price_1RgBCyItbmi22a3Lf9UqDCvm",
        active: false,
        unitAmountInCents: 52500,
        unitAmount: 525,
        percentOff: null,
        discountedUnitAmount: null,
        productType: 19,
        type: "recurring",
        recurring: {
          interval: "year",
          intervalCount: 1,
        },
        currency: "usd",
      },
    ],
    trialHandbook: {
      allowed: true,
      requirePayment: false,
      expireDate: "2023-02-09T03:59:09.471Z",
      allowedDownload: false,
      autoUpdate: true,
      collaboration: true,
      eSignature: true,
      accessCreationConfig: 0,
    },
    partnerSetting: null,
    tab: 1,
  },
  {
    planId: null,
    masterPlanId: "651e27c093364c46c651e4b4",
    name: "Under 50 Employees",
    description: "This package is best suited for companies under 50 employees",
    isCustom: false,
    freeTrialAllowed: true,
    companySize: "Under 50 Employees",
    benefits: [
      {
        benefit: "Unlimited Licenses",
        benefitKey: "benefit-1",
        requiredPayment: false,
        isSame: true,
      },
      {
        benefit: "Unlimited Business Licenses",
        benefitKey: "benefit-10",
        requiredPayment: false,
        isSame: true,
      },
      {
        benefit: "Unlimited Chatbot Chats",
        benefitKey: "benefit-2",
        requiredPayment: false,
        isSame: true,
      },
      {
        benefit: "Contact an HR Expert once/month/user",
        benefitKey: "benefit-7",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit: "Multi-state Comparison Tool",
        benefitKey: "benefit-3",
        requiredPayment: false,
        isSame: true,
      },
      {
        benefit: "Legal Updates",
        benefitKey: "benefit-5",
        requiredPayment: false,
        isSame: true,
      },
      {
        benefit: "Unlimited Handbooks",
        benefitKey: "benefit-6",
        requiredPayment: false,
        isSame: true,
      },
      {
        benefit:
          "Policy Templates, Job Descriptions, Employment Agreements, and more",
        benefitKey: "benefit-4",
        requiredPayment: false,
        isSame: true,
      },
    ],
    benefitsTrial: [
      {
        benefit: "Unlimited Licenses",
        benefitKey: "benefit-1",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit: "Unlimited Business Licenses",
        benefitKey: "benefit-10",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit: "Unlimited Chatbot Chats",
        benefitKey: "benefit-2",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit: "Contact an HR Expert once/month/user",
        benefitKey: "benefit-7",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit: "Multi-state Comparison Tool",
        benefitKey: "benefit-3",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit: "Legal Updates",
        benefitKey: "benefit-5",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit: "Unlimited Handbooks",
        benefitKey: "benefit-6",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit:
          "Policy Templates, Job Descriptions, Employment Agreements, and more",
        benefitKey: "benefit-4",
        requiredPayment: false,
        isSame: false,
      },
    ],
    prices: [
      {
        id: "price_1RgBBYItbmi22a3LbKwMg895",
        active: false,
        unitAmountInCents: 10500,
        unitAmount: 105,
        percentOff: null,
        discountedUnitAmount: null,
        productType: 15,
        type: "recurring",
        recurring: {
          interval: "month",
          intervalCount: 1,
        },
        currency: "usd",
      },
      {
        id: "price_1RgBBZItbmi22a3LvHxvvHV7",
        active: false,
        unitAmountInCents: 105000,
        unitAmount: 1050,
        percentOff: null,
        discountedUnitAmount: null,
        productType: 1,
        type: "recurring",
        recurring: {
          interval: "year",
          intervalCount: 1,
        },
        currency: "usd",
      },
    ],
    trialHandbook: {
      allowed: true,
      requirePayment: false,
      expireDate: "2023-02-09T03:59:09.471Z",
      allowedDownload: false,
      autoUpdate: true,
      collaboration: true,
      eSignature: true,
      accessCreationConfig: 0,
    },
    partnerSetting: null,
    tab: 0,
  },
  {
    planId: null,
    masterPlanId: "65a89cd8d6162bcce7a5eb6d",
    name: "50 - 100 Employees",
    description: null,
    isCustom: false,
    freeTrialAllowed: true,
    companySize: "50 - 100 Employees",
    benefits: [
      {
        benefit: "Unlimited Licenses",
        benefitKey: "benefit-1",
        requiredPayment: false,
        isSame: true,
      },
      {
        benefit: "Unlimited Business Licenses",
        benefitKey: "benefit-10",
        requiredPayment: false,
        isSame: true,
      },
      {
        benefit: "Unlimited Chatbot Chats",
        benefitKey: "benefit-2",
        requiredPayment: false,
        isSame: true,
      },
      {
        benefit: "Contact an HR Expert twice/month/user",
        benefitKey: "benefit-7",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit: "Multi-state Comparison Tool",
        benefitKey: "benefit-3",
        requiredPayment: false,
        isSame: true,
      },
      {
        benefit: "Legal Updates",
        benefitKey: "benefit-5",
        requiredPayment: false,
        isSame: true,
      },
      {
        benefit: "Unlimited Handbooks",
        benefitKey: "benefit-6",
        requiredPayment: false,
        isSame: true,
      },
      {
        benefit:
          "Policy Templates, Job Descriptions, Employment Agreements, and more",
        benefitKey: "benefit-4",
        requiredPayment: false,
        isSame: true,
      },
    ],
    benefitsTrial: [
      {
        benefit: "Unlimited Licenses",
        benefitKey: "benefit-1",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit: "Unlimited Business Licenses",
        benefitKey: "benefit-10",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit: "Unlimited Chatbot Chats",
        benefitKey: "benefit-2",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit: "Contact an HR Expert twice/month/user",
        benefitKey: "benefit-7",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit: "Multi-state Comparison Tool",
        benefitKey: "benefit-3",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit: "Legal Updates",
        benefitKey: "benefit-5",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit: "Unlimited Handbooks",
        benefitKey: "benefit-6",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit:
          "Policy Templates, Job Descriptions, Employment Agreements, and more",
        benefitKey: "benefit-4",
        requiredPayment: false,
        isSame: false,
      },
    ],
    prices: [
      {
        id: "price_1RgBBwItbmi22a3L2HWHWOqp",
        active: false,
        unitAmountInCents: 15500,
        unitAmount: 155,
        percentOff: null,
        discountedUnitAmount: null,
        productType: 16,
        type: "recurring",
        recurring: {
          interval: "month",
          intervalCount: 1,
        },
        currency: "usd",
      },
      {
        id: "price_1RgBBwItbmi22a3L1zRLpr87",
        active: false,
        unitAmountInCents: 155000,
        unitAmount: 1550,
        percentOff: null,
        discountedUnitAmount: null,
        productType: 17,
        type: "recurring",
        recurring: {
          interval: "year",
          intervalCount: 1,
        },
        currency: "usd",
      },
    ],
    trialHandbook: {
      allowed: true,
      requirePayment: false,
      expireDate: "2023-02-09T03:59:09.471Z",
      allowedDownload: false,
      autoUpdate: true,
      collaboration: true,
      eSignature: true,
      accessCreationConfig: 0,
    },
    partnerSetting: null,
    tab: 0,
  },
  {
    planId: null,
    masterPlanId: "651e27c093364c46c651e4b3",
    name: "101 - 250 Employees",
    description:
      "This package is best suited for companies between 50-250 employees",
    isCustom: false,
    freeTrialAllowed: true,
    companySize: "101 - 250 Employees",
    benefits: [
      {
        benefit: "Unlimited Licenses",
        benefitKey: "benefit-1",
        requiredPayment: false,
        isSame: true,
      },
      {
        benefit: "Unlimited Business Licenses",
        benefitKey: "benefit-10",
        requiredPayment: false,
        isSame: true,
      },
      {
        benefit: "Unlimited Chatbot Chats",
        benefitKey: "benefit-2",
        requiredPayment: false,
        isSame: true,
      },
      {
        benefit: "Contact an HR Expert 3 times/month/user",
        benefitKey: "benefit-7",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit: "Multi-state Comparison Tool",
        benefitKey: "benefit-3",
        requiredPayment: false,
        isSame: true,
      },
      {
        benefit: "Legal Updates",
        benefitKey: "benefit-5",
        requiredPayment: false,
        isSame: true,
      },
      {
        benefit: "Unlimited Handbooks",
        benefitKey: "benefit-6",
        requiredPayment: false,
        isSame: true,
      },
      {
        benefit:
          "Policy Templates, Job Descriptions, Employment Agreements, and more",
        benefitKey: "benefit-4",
        requiredPayment: false,
        isSame: true,
      },
    ],
    benefitsTrial: [
      {
        benefit: "Unlimited Licenses",
        benefitKey: "benefit-1",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit: "Unlimited Business Licenses",
        benefitKey: "benefit-10",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit: "Unlimited Chatbot Chats",
        benefitKey: "benefit-2",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit: "Contact an HR Expert 3 times/month/user",
        benefitKey: "benefit-7",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit: "Multi-state Comparison Tool",
        benefitKey: "benefit-3",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit: "Legal Updates",
        benefitKey: "benefit-5",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit: "Unlimited Handbooks",
        benefitKey: "benefit-6",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit:
          "Policy Templates, Job Descriptions, Employment Agreements, and more",
        benefitKey: "benefit-4",
        requiredPayment: false,
        isSame: false,
      },
    ],
    prices: [
      {
        id: "price_1RgBCCItbmi22a3LUsv6bNef",
        active: false,
        unitAmountInCents: 27000,
        unitAmount: 270,
        percentOff: null,
        discountedUnitAmount: null,
        productType: 2,
        type: "recurring",
        recurring: {
          interval: "month",
          intervalCount: 1,
        },
        currency: "usd",
      },
      {
        id: "price_1RgBCDItbmi22a3LPKczXBYh",
        active: false,
        unitAmountInCents: 270000,
        unitAmount: 2700,
        percentOff: null,
        discountedUnitAmount: null,
        productType: 3,
        type: "recurring",
        recurring: {
          interval: "year",
          intervalCount: 1,
        },
        currency: "usd",
      },
    ],
    trialHandbook: {
      allowed: true,
      requirePayment: false,
      expireDate: "2023-02-09T03:59:09.471Z",
      allowedDownload: false,
      autoUpdate: true,
      collaboration: true,
      eSignature: true,
      accessCreationConfig: 0,
    },
    partnerSetting: null,
    tab: 0,
  },
  {
    planId: null,
    masterPlanId: "651e27bf93364c46c651e4b2",
    name: "251 - 500 Employees",
    description:
      "This package is best suited for companies between 250-1000 employees",
    isCustom: false,
    freeTrialAllowed: true,
    companySize: "251 - 500 Employees",
    benefits: [
      {
        benefit: "Unlimited Licenses",
        benefitKey: "benefit-1",
        requiredPayment: false,
        isSame: true,
      },
      {
        benefit: "Unlimited Business Licenses",
        benefitKey: "benefit-10",
        requiredPayment: false,
        isSame: true,
      },
      {
        benefit: "Unlimited Chatbot Chats",
        benefitKey: "benefit-2",
        requiredPayment: false,
        isSame: true,
      },
      {
        benefit: "Contact an HR Expert 4 times/month/user",
        benefitKey: "benefit-7",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit: "Multi-state Comparison Tool",
        benefitKey: "benefit-3",
        requiredPayment: false,
        isSame: true,
      },
      {
        benefit: "Legal Updates",
        benefitKey: "benefit-5",
        requiredPayment: false,
        isSame: true,
      },
      {
        benefit: "Unlimited Handbooks",
        benefitKey: "benefit-6",
        requiredPayment: false,
        isSame: true,
      },
      {
        benefit:
          "Policy Templates, Job Descriptions, Employment Agreements, and more",
        benefitKey: "benefit-4",
        requiredPayment: false,
        isSame: true,
      },
    ],
    benefitsTrial: [
      {
        benefit: "Unlimited Licenses",
        benefitKey: "benefit-1",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit: "Unlimited Business Licenses",
        benefitKey: "benefit-10",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit: "Unlimited Chatbot Chats",
        benefitKey: "benefit-2",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit: "Contact an HR Expert 4 times/month/user",
        benefitKey: "benefit-7",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit: "Multi-state Comparison Tool",
        benefitKey: "benefit-3",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit: "Legal Updates",
        benefitKey: "benefit-5",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit: "Unlimited Handbooks",
        benefitKey: "benefit-6",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit:
          "Policy Templates, Job Descriptions, Employment Agreements, and more",
        benefitKey: "benefit-4",
        requiredPayment: false,
        isSame: false,
      },
    ],
    prices: [
      {
        id: "price_1RgBCRItbmi22a3LS4WCgZrJ",
        active: false,
        unitAmountInCents: 44000,
        unitAmount: 440,
        percentOff: null,
        discountedUnitAmount: null,
        productType: 4,
        type: "recurring",
        recurring: {
          interval: "month",
          intervalCount: 1,
        },
        currency: "usd",
      },
      {
        id: "price_1RgBCRItbmi22a3LUNeDrVjP",
        active: false,
        unitAmountInCents: 440000,
        unitAmount: 4400,
        percentOff: null,
        discountedUnitAmount: null,
        productType: 5,
        type: "recurring",
        recurring: {
          interval: "year",
          intervalCount: 1,
        },
        currency: "usd",
      },
    ],
    trialHandbook: {
      allowed: true,
      requirePayment: false,
      expireDate: "2023-02-09T03:59:09.471Z",
      allowedDownload: false,
      autoUpdate: true,
      collaboration: true,
      eSignature: true,
      accessCreationConfig: 0,
    },
    partnerSetting: null,
    tab: 0,
  },
  {
    planId: null,
    masterPlanId: "651e27bf93364c46c651e4b1",
    name: "500+ Employees & HR Consultants",
    description: "Customized solution that meets all of your requirements",
    isCustom: true,
    freeTrialAllowed: true,
    companySize: "500+ Employees & HR Consultants",
    benefits: [
      {
        benefit: "Unlimited Licenses",
        benefitKey: "benefit-1",
        requiredPayment: false,
        isSame: true,
      },
      {
        benefit: "Unlimited Business Licenses",
        benefitKey: "benefit-10",
        requiredPayment: false,
        isSame: true,
      },
      {
        benefit: "Unlimited Chatbot Chats",
        benefitKey: "benefit-2",
        requiredPayment: false,
        isSame: true,
      },
      {
        benefit: "Contact an HR Expert 5 times/month/user",
        benefitKey: "benefit-7",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit: "Multi-state Comparison Tool",
        benefitKey: "benefit-3",
        requiredPayment: false,
        isSame: true,
      },
      {
        benefit: "Legal Updates",
        benefitKey: "benefit-5",
        requiredPayment: false,
        isSame: true,
      },
      {
        benefit: "Unlimited Handbooks",
        benefitKey: "benefit-6",
        requiredPayment: false,
        isSame: true,
      },
      {
        benefit:
          "Policy Templates, Job Descriptions, Employment Agreements, and more",
        benefitKey: "benefit-4",
        requiredPayment: false,
        isSame: true,
      },
    ],
    benefitsTrial: [
      {
        benefit: "Unlimited Licenses",
        benefitKey: "benefit-1",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit: "Unlimited Business Licenses",
        benefitKey: "benefit-10",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit: "Unlimited Chatbot Chats",
        benefitKey: "benefit-2",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit: "Contact an HR Expert 5 times/month/user",
        benefitKey: "benefit-7",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit: "Multi-state Comparison Tool",
        benefitKey: "benefit-3",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit: "Legal Updates",
        benefitKey: "benefit-5",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit: "Unlimited Handbooks",
        benefitKey: "benefit-6",
        requiredPayment: false,
        isSame: false,
      },
      {
        benefit:
          "Policy Templates, Job Descriptions, Employment Agreements, and more",
        benefitKey: "benefit-4",
        requiredPayment: false,
        isSame: false,
      },
    ],
    prices: [],
    trialHandbook: {
      allowed: true,
      requirePayment: false,
      expireDate: "2023-02-09T03:59:09.471Z",
      allowedDownload: false,
      autoUpdate: true,
      collaboration: true,
      eSignature: true,
      accessCreationConfig: 0,
    },
    partnerSetting: null,
    tab: 0,
  },
];
