{
  "plans": [],
  "partners": [],
  "teams": [],
  "total": 1,
  "entities": [
    {
      "consumerObjectId": "699c893734165dad7f84f7d4",
      "planObjectId": null,
      "teamObjectId": null,
      "consumers": {
        "firstName": "Karine",
        "normalizedFirstName": "KARINE",
        "lastName": "Baumbach",
        "normalizedLastName": "BAUMBACH",
        "fullName": "Karine Baumbach",
        "normalizedFullName": "KARINE BAUMBACH",
        "email": "TeamVin07@yopmail.com",
        "normalizedEmail": "TEAMVIN07@YOPMAIL.COM",
        "jobTitle": "National Branding Director",
        "companyName": "TeamVin07",
        "companySize": "",
        "profilePicture": null,
        "phoneNumber": "+14938658613",
        "address": null,
        "country": {
          "key": "US",
          "value": "United States"
        },
        "state": null,
        "announcementStates": [
          {
            "teamId": null,
            "states": []
          }
        ],
        "timeZone": null,
        "dateOfBirth": null,
        "isActive": true,
        "lastActive": "0001-01-01T00:00:00Z",
        "casesFriendlyIdCounter": "00001",
        "exampleFriendlyId": null,
        "totalIndividualCases": 0,
        "teamIds": [],
        "partnerInfos": [],
        "departmentId": "688897d5eb52b4af5573def4",
        "tutorialSettings": null,
        "miscellaneousSettings": null,
        "label": [],
        "userType": 1,
        "latestAnnouncementClosed": null,
        "contactId": null,
        "accountId": null,
        "recentData": null,
        "upcomingChangeStateIds": null,
        "source": "virgilhr",
        "isSso": false,
        "provider": null,
        "currentTeam": null,
        "currentPartner": null,
        "externalId": null,
        "externalEmployeeId": null,
        "externalIds": null,
        "department": null,
        "employeeStatus": null,
        "consumerType": 1,
        "thirdPartyIds": null,
        "version": 0,
        "createdAt": "2026-02-23T17:07:03.413Z",
        "updatedAt": "2026-02-23T17:07:03.413Z",
        "createdBy": null,
        "updatedBy": null,
        "isDeleted": false,
        "id": "699c893734165dad7f84f7d4"
      },
      "plans": null,
      "teams": null,
      "partner": null,
      "consumerTeamConfigs": [],
      "emailConfirmed": true,
      "stripeCustomerId": null,
      "subscription": null
    }
  ]
}