{
  "plans": [
    {
      "name": "Old Team Monthlhy",
      "productType": 10,
      "licenseQuantity": 3,
      "isActive": false,
      "price": {
        "id": "price_1LhrIMBhKjoN79jawxjq95gk",
        "unitAmountInCents": 17900,
        "unitAmount": 179,
        "type": "recurring",
        "productType": 0,
        "recurring": {
          "interval": "month",
          "intervalCount": 1
        },
        "currency": "usd"
      },
      "version": 0,
      "createdAt": "2023-02-14T08:26:16.255Z",
      "updatedAt": "2023-02-14T08:26:16.255Z",
      "createdBy": null,
      "updatedBy": null,
      "isDeleted": false,
      "id": "63eb45a8c80d8549e6d4fedc"
    }
  ],
  "partners": [],
  "teams": [
    {
      "name": "Banana v45",
      "normalizedName": "BANANA V45",
      "code": "BANANA",
      "contactEmail": "tam.mai@bigin.vn",
      "contactPhone": "+10984746223",
      "invoiceEmail": "tam.mai@bigin.vn",
      "profilePicture": "https://s3-ap-southeast-1.amazonaws.com/virgil.qa/public/surprise.png1658981389826",
      "coverPhoto": null,
      "members": [],
      "partnerId": null,
      "subDomain": null,
      "departmentId": "688897d5eb52b4af5573def4",
      "source": "virgilhr",
      "isActive": true,
      "casesFriendlyIdCounter": "00024",
      "totalCases": 18,
      "label": [],
      "createHistoryTaskBaseOnAnnouncements": null,
      "backUrl": null,
      "backText": null,
      "assignedIds": [],
      "externalCompanyId": null,
      "version": 0,
      "createdAt": "2022-08-25T03:09:33.925Z",
      "updatedAt": "2022-08-25T03:09:33.925Z",
      "createdBy": null,
      "updatedBy": null,
      "isDeleted": false,
      "id": "6306e7ed017b48f3e7dc496c"
    },
    {
      "name": "s",
      "normalizedName": "S",
      "code": "S-BK53SU",
      "contactEmail": null,
      "contactPhone": null,
      "invoiceEmail": null,
      "profilePicture": null,
      "coverPhoto": null,
      "members": [],
      "partnerId": null,
      "subDomain": null,
      "departmentId": "688897d5eb52b4af5573def4",
      "source": "virgilhr",
      "isActive": true,
      "casesFriendlyIdCounter": "00001",
      "totalCases": 0,
      "label": [],
      "createHistoryTaskBaseOnAnnouncements": null,
      "backUrl": null,
      "backText": null,
      "assignedIds": [],
      "externalCompanyId": null,
      "version": 0,
      "createdAt": "2022-08-27T10:44:01.307Z",
      "updatedAt": "2022-08-27T10:44:01.307Z",
      "createdBy": null,
      "updatedBy": null,
      "isDeleted": false,
      "id": "6309f571b851e199d3a0f4c0"
    },
    {
      "name": "ENter",
      "normalizedName": "ENTER",
      "code": "ENT-100B3H",
      "contactEmail": null,
      "contactPhone": null,
      "invoiceEmail": null,
      "profilePicture": null,
      "coverPhoto": null,
      "members": [],
      "partnerId": null,
      "subDomain": null,
      "departmentId": "688897d5eb52b4af5573def4",
      "source": "virgilhr",
      "isActive": true,
      "casesFriendlyIdCounter": "00005",
      "totalCases": 3,
      "label": [],
      "createHistoryTaskBaseOnAnnouncements": null,
      "backUrl": null,
      "backText": null,
      "assignedIds": [],
      "externalCompanyId": null,
      "version": 0,
      "createdAt": "2022-08-28T02:24:33.672Z",
      "updatedAt": "2022-08-28T02:24:33.672Z",
      "createdBy": null,
      "updatedBy": null,
      "isDeleted": false,
      "id": "630ad1e10d294947f1fc6920"
    },
    {
      "name": "Sun",
      "normalizedName": "SUN",
      "code": "A S-RBX3EP",
      "contactEmail": "dtesting9@yopmail.com",
      "contactPhone": "+1312313131",
      "invoiceEmail": "31321323",
      "profilePicture": null,
      "coverPhoto": null,
      "members": [],
      "partnerId": null,
      "subDomain": null,
      "departmentId": "688897d5eb52b4af5573def4",
      "source": "virgilhr",
      "isActive": true,
      "casesFriendlyIdCounter": "00069",
      "totalCases": 50,
      "label": [],
      "createHistoryTaskBaseOnAnnouncements": null,
      "backUrl": null,
      "backText": null,
      "assignedIds": [],
      "externalCompanyId": null,
      "version": 0,
      "createdAt": "2022-08-28T04:46:04.559Z",
      "updatedAt": "2022-08-28T04:46:04.559Z",
      "createdBy": null,
      "updatedBy": null,
      "isDeleted": false,
      "id": "630af30c0d294947f1fc7930"
    }
  ],
  "total": 4814,
  "entities": [
    {
      "consumerObjectId": "62da7106342a650f0af96499",
      "planObjectId": null,
      "teamObjectId": null,
      "consumers": {
        "firstName": "Danh",
        "normalizedFirstName": "DANH",
        "lastName": "Nguyen",
        "normalizedLastName": "NGUYEN",
        "fullName": "Danh Nguyen",
        "normalizedFullName": "DANH NGUYEN",
        "email": "danh.nguyen@bigin.vn",
        "normalizedEmail": "DANH.NGUYEN@BIGIN.VN",
        "jobTitle": "Head of Design",
        "companyName": "BigIn JSC",
        "companySize": null,
        "profilePicture": null,
        "phoneNumber": "+151555555",
        "address": "138/30 Trương Công Định, Tân Bình",
        "country": {
          "key": "US",
          "value": "United States"
        },
        "state": {
          "key": "AZ",
          "value": "Arizona"
        },
        "announcementStates": [
          {
            "teamId": null,
            "states": []
          }
        ],
        "timeZone": "(UTC+07:00) Vietnam",
        "dateOfBirth": "1989-12-28T17:00:00Z",
        "isActive": true,
        "lastActive": "2023-11-02T02:54:02.249Z",
        "casesFriendlyIdCounter": "00001",
        "exampleFriendlyId": null,
        "totalIndividualCases": 16,
        "teamIds": [],
        "partnerInfos": [],
        "departmentId": "688897d5eb52b4af5573def4",
        "tutorialSettings": null,
        "miscellaneousSettings": null,
        "label": [],
        "userType": 0,
        "latestAnnouncementClosed": null,
        "contactId": null,
        "accountId": null,
        "recentData": null,
        "upcomingChangeStateIds": null,
        "source": "member",
        "isSso": null,
        "provider": null,
        "currentTeam": null,
        "currentPartner": null,
        "externalId": null,
        "externalEmployeeId": null,
        "externalIds": null,
        "department": null,
        "employeeStatus": null,
        "consumerType": 1,
        "thirdPartyIds": null,
        "version": 0,
        "createdAt": "2022-07-22T09:42:30.341Z",
        "updatedAt": "2022-07-22T09:42:30.341Z",
        "createdBy": null,
        "updatedBy": null,
        "isDeleted": false,
        "id": "62da7106342a650f0af96499"
      },
      "plans": null,
      "teams": null,
      "partner": null,
      "consumerTeamConfigs": [],
      "emailConfirmed": true,
      "stripeCustomerId": "632c1254f4705941c0bc1bdb",
      "subscription": {
        "name": null,
        "planId": null,
        "stripeProductId": null,
        "productType": 11,
        "accountType": 2,
        "quantity": 1,
        "startDate": "2022-10-25T03:46:16Z",
        "endDate": "2022-11-24T03:46:16Z",
        "contractStartDate": null,
        "contractEndDate": null,
        "isTrial": true,
        "isCanceled": true,
        "isPaymentLate": false,
        "cancelAtPeriodEnd": false,
        "canceledBy": null,
        "canceledDate": null,
        "cancellationReason": 0,
        "stripeCouponId": null,
        "percentOff": null,
        "amountOff": null
      }
    },
    {
      "consumerObjectId": "62de6033342a650f0af971ac",
      "planObjectId": null,
      "teamObjectId": null,
      "consumers": {
        "firstName": "Duong",
        "normalizedFirstName": "DUONG",
        "lastName": "Phan",
        "normalizedLastName": "PHAN",
        "fullName": "Duong Phan",
        "normalizedFullName": "DUONG PHAN",
        "email": "dptesting9@gmail.com",
        "normalizedEmail": "DPTESTING9@GMAIL.COM",
        "jobTitle": null,
        "companyName": null,
        "companySize": null,
        "profilePicture": null,
        "phoneNumber": "",
        "address": null,
        "country": null,
        "state": null,
        "announcementStates": [
          {
            "teamId": "630ad1e10d294947f1fc6920",
            "states": []
          }
        ],
        "timeZone": null,
        "dateOfBirth": null,
        "isActive": true,
        "lastActive": "2022-12-29T03:32:27.456Z",
        "casesFriendlyIdCounter": "00004",
        "exampleFriendlyId": null,
        "totalIndividualCases": 2,
        "teamIds": [
          "630ad1e10d294947f1fc6920"
        ],
        "partnerInfos": [],
        "departmentId": "688897d5eb52b4af5573def4",
        "tutorialSettings": null,
        "miscellaneousSettings": null,
        "label": [],
        "userType": 0,
        "latestAnnouncementClosed": null,
        "contactId": null,
        "accountId": null,
        "recentData": null,
        "upcomingChangeStateIds": null,
        "source": "member",
        "isSso": null,
        "provider": null,
        "currentTeam": null,
        "currentPartner": null,
        "externalId": null,
        "externalEmployeeId": null,
        "externalIds": null,
        "department": null,
        "employeeStatus": null,
        "consumerType": 1,
        "thirdPartyIds": null,
        "version": 0,
        "createdAt": "2022-07-25T09:19:47.924Z",
        "updatedAt": "2022-07-25T09:19:47.924Z",
        "createdBy": null,
        "updatedBy": null,
        "isDeleted": false,
        "id": "62de6033342a650f0af971ac"
      },
      "plans": null,
      "teams": null,
      "partner": null,
      "consumerTeamConfigs": [],
      "emailConfirmed": true,
      "stripeCustomerId": "632c1255f4705941c0bc1bdc",
      "subscription": {
        "name": null,
        "planId": null,
        "stripeProductId": null,
        "productType": 10,
        "accountType": 2,
        "quantity": 2,
        "startDate": "2022-10-25T03:46:18Z",
        "endDate": "2022-11-24T03:46:18Z",
        "contractStartDate": null,
        "contractEndDate": null,
        "isTrial": true,
        "isCanceled": true,
        "isPaymentLate": false,
        "cancelAtPeriodEnd": false,
        "canceledBy": null,
        "canceledDate": null,
        "cancellationReason": 0,
        "stripeCouponId": null,
        "percentOff": null,
        "amountOff": null
      }
    },
    {
      "consumerObjectId": "62fb772e50212f2cbeb9dbc9",
      "planObjectId": null,
      "teamObjectId": null,
      "consumers": {
        "firstName": "Duyn",
        "normalizedFirstName": "DUYN",
        "lastName": "Huyn",
        "normalizedLastName": "HUYN",
        "fullName": "Duyn Huyn",
        "normalizedFullName": "DUYN HUYN",
        "email": "tranhuynhcamduyen@gmail.com",
        "normalizedEmail": "TRANHUYNHCAMDUYEN@GMAIL.COM",
        "jobTitle": null,
        "companyName": null,
        "companySize": null,
        "profilePicture": null,
        "phoneNumber": null,
        "address": null,
        "country": null,
        "state": null,
        "announcementStates": [
          {
            "teamId": null,
            "states": []
          }
        ],
        "timeZone": null,
        "dateOfBirth": null,
        "isActive": true,
        "lastActive": "2022-08-28T08:45:31.139Z",
        "casesFriendlyIdCounter": "00001",
        "exampleFriendlyId": null,
        "totalIndividualCases": 2,
        "teamIds": [],
        "partnerInfos": [],
        "departmentId": "688897d5eb52b4af5573def4",
        "tutorialSettings": null,
        "miscellaneousSettings": null,
        "label": [],
        "userType": 0,
        "latestAnnouncementClosed": null,
        "contactId": null,
        "accountId": null,
        "recentData": null,
        "upcomingChangeStateIds": null,
        "source": "member",
        "isSso": null,
        "provider": null,
        "currentTeam": null,
        "currentPartner": null,
        "externalId": null,
        "externalEmployeeId": null,
        "externalIds": null,
        "department": null,
        "employeeStatus": null,
        "consumerType": 1,
        "thirdPartyIds": null,
        "version": 0,
        "createdAt": "2022-08-16T10:53:34.419Z",
        "updatedAt": "2022-08-16T10:53:34.419Z",
        "createdBy": null,
        "updatedBy": null,
        "isDeleted": false,
        "id": "62fb772e50212f2cbeb9dbc9"
      },
      "plans": null,
      "teams": null,
      "partner": null,
      "consumerTeamConfigs": [],
      "emailConfirmed": true,
      "stripeCustomerId": "632c125df4705941c0bc1be9",
      "subscription": {
        "name": null,
        "planId": null,
        "stripeProductId": null,
        "productType": 11,
        "accountType": 2,
        "quantity": 1,
        "startDate": "2022-10-25T03:46:34Z",
        "endDate": "2022-11-24T03:46:34Z",
        "contractStartDate": null,
        "contractEndDate": null,
        "isTrial": true,
        "isCanceled": true,
        "isPaymentLate": false,
        "cancelAtPeriodEnd": false,
        "canceledBy": null,
        "canceledDate": null,
        "cancellationReason": 0,
        "stripeCouponId": null,
        "percentOff": null,
        "amountOff": null
      }
    },
    {
      "consumerObjectId": "6309d195b851e199d3a0f36f",
      "planObjectId": null,
      "teamObjectId": null,
      "consumers": {
        "firstName": "Tam",
        "normalizedFirstName": "TAM",
        "lastName": "Mai+1",
        "normalizedLastName": "MAI+1",
        "fullName": "Tam Mai+1",
        "normalizedFullName": "TAM MAI+1",
        "email": "tammai.it+1@gmail.com",
        "normalizedEmail": "TAMMAI.IT+1@GMAIL.COM",
        "jobTitle": "Manager",
        "companyName": "BigIn",
        "companySize": "100",
        "profilePicture": null,
        "phoneNumber": null,
        "address": null,
        "country": null,
        "state": null,
        "announcementStates": [
          {
            "teamId": "6306e7ed017b48f3e7dc496c",
            "states": []
          },
          {
            "teamId": "6309f571b851e199d3a0f4c0",
            "states": []
          }
        ],
        "timeZone": null,
        "dateOfBirth": null,
        "isActive": true,
        "lastActive": "2022-08-29T07:55:01.711Z",
        "casesFriendlyIdCounter": "00001",
        "exampleFriendlyId": null,
        "totalIndividualCases": 0,
        "teamIds": [
          "6306e7ed017b48f3e7dc496c",
          "6309f571b851e199d3a0f4c0"
        ],
        "partnerInfos": [],
        "departmentId": "688897d5eb52b4af5573def4",
        "tutorialSettings": null,
        "miscellaneousSettings": null,
        "label": [],
        "userType": 0,
        "latestAnnouncementClosed": null,
        "contactId": null,
        "accountId": null,
        "recentData": null,
        "upcomingChangeStateIds": null,
        "source": "member",
        "isSso": null,
        "provider": null,
        "currentTeam": null,
        "currentPartner": null,
        "externalId": null,
        "externalEmployeeId": null,
        "externalIds": null,
        "department": null,
        "employeeStatus": null,
        "consumerType": 1,
        "thirdPartyIds": null,
        "version": 0,
        "createdAt": "2022-08-27T08:11:01.733Z",
        "updatedAt": "2022-08-27T08:11:01.733Z",
        "createdBy": null,
        "updatedBy": null,
        "isDeleted": false,
        "id": "6309d195b851e199d3a0f36f"
      },
      "plans": null,
      "teams": null,
      "partner": null,
      "consumerTeamConfigs": [],
      "emailConfirmed": true,
      "stripeCustomerId": "632c1262f4705941c0bc1bf1",
      "subscription": {
        "name": null,
        "planId": null,
        "stripeProductId": null,
        "productType": 10,
        "accountType": 2,
        "quantity": 6,
        "startDate": "2022-10-25T03:46:26Z",
        "endDate": "2022-11-24T03:46:26Z",
        "contractStartDate": null,
        "contractEndDate": null,
        "isTrial": true,
        "isCanceled": true,
        "isPaymentLate": false,
        "cancelAtPeriodEnd": false,
        "canceledBy": null,
        "canceledDate": null,
        "cancellationReason": 0,
        "stripeCouponId": null,
        "percentOff": null,
        "amountOff": null
      }
    },
    {
      "consumerObjectId": "62de6315342a650f0af972a5",
      "planObjectId": "63eb45a8c80d8549e6d4fedc",
      "teamObjectId": null,
      "consumers": {
        "firstName": "Duong",
        "normalizedFirstName": "DUONG",
        "lastName": "Phan",
        "normalizedLastName": "PHAN",
        "fullName": "Duong Phan",
        "normalizedFullName": "DUONG PHAN",
        "email": "duong.phan@bigin.vn",
        "normalizedEmail": "DUONG.PHAN@BIGIN.VN",
        "jobTitle": "AB",
        "companyName": "AA",
        "companySize": null,
        "profilePicture": "https://s3-ap-southeast-1.amazonaws.com/virgil.qa/public/357367989_659931256179207_5986835565681141751_n.jpg1688960336095",
        "phoneNumber": "",
        "address": null,
        "country": null,
        "state": null,
        "announcementStates": [
          {
            "teamId": "630af30c0d294947f1fc7930",
            "states": [
              {
                "key": "AK",
                "value": "Alaska"
              },
              {
                "key": "AR",
                "value": "Arkansas"
              },
              {
                "key": "CT",
                "value": "Connecticut"
              },
              {
                "key": "National",
                "value": "National"
              }
            ]
          }
        ],
        "timeZone": "(UTC-04:00) Anguilla",
        "dateOfBirth": null,
        "isActive": true,
        "lastActive": "2023-10-24T06:04:31.894Z",
        "casesFriendlyIdCounter": "00010",
        "exampleFriendlyId": null,
        "totalIndividualCases": 84,
        "teamIds": [
          "630af30c0d294947f1fc7930"
        ],
        "partnerInfos": [],
        "departmentId": "688897d5eb52b4af5573def4",
        "tutorialSettings": null,
        "miscellaneousSettings": null,
        "label": [],
        "userType": 0,
        "latestAnnouncementClosed": "2023-07-27T03:32:43Z",
        "contactId": null,
        "accountId": null,
        "recentData": null,
        "upcomingChangeStateIds": [
          "National"
        ],
        "source": "member",
        "isSso": null,
        "provider": null,
        "currentTeam": null,
        "currentPartner": null,
        "externalId": null,
        "externalEmployeeId": null,
        "externalIds": null,
        "department": null,
        "employeeStatus": null,
        "consumerType": 1,
        "thirdPartyIds": null,
        "version": 0,
        "createdAt": "2022-07-25T09:32:05.596Z",
        "updatedAt": "2022-07-25T09:32:05.596Z",
        "createdBy": null,
        "updatedBy": null,
        "isDeleted": false,
        "id": "62de6315342a650f0af972a5"
      },
      "plans": null,
      "teams": null,
      "partner": null,
      "consumerTeamConfigs": [],
      "emailConfirmed": true,
      "stripeCustomerId": "632c1264f4705941c0bc1bf5",
      "subscription": {
        "name": "Old Team Monthlhy",
        "planId": "63eb45a8c80d8549e6d4fedc",
        "stripeProductId": null,
        "productType": 10,
        "accountType": 3,
        "quantity": 11,
        "startDate": "2023-01-24T03:57:29Z",
        "endDate": "2023-02-24T03:57:29Z",
        "contractStartDate": null,
        "contractEndDate": null,
        "isTrial": false,
        "isCanceled": false,
        "isPaymentLate": null,
        "cancelAtPeriodEnd": false,
        "canceledBy": null,
        "canceledDate": null,
        "cancellationReason": 0,
        "stripeCouponId": null,
        "percentOff": null,
        "amountOff": null
      }
    },
    {
      "consumerObjectId": "62ea0192d27a0fab6f916f0a",
      "planObjectId": null,
      "teamObjectId": null,
      "consumers": {
        "firstName": "Binh",
        "normalizedFirstName": "BINH",
        "lastName": "Tran",
        "normalizedLastName": "TRAN",
        "fullName": "Binh Tran",
        "normalizedFullName": "BINH TRAN",
        "email": "binh.tran@bigin.vn",
        "normalizedEmail": "BINH.TRAN@BIGIN.VN",
        "jobTitle": null,
        "companyName": null,
        "companySize": null,
        "profilePicture": null,
        "phoneNumber": null,
        "address": null,
        "country": null,
        "state": null,
        "announcementStates": [
          {
            "teamId": null,
            "states": []
          }
        ],
        "timeZone": null,
        "dateOfBirth": null,
        "isActive": true,
        "lastActive": "2022-11-02T10:40:17.738Z",
        "casesFriendlyIdCounter": "00001",
        "exampleFriendlyId": null,
        "totalIndividualCases": 0,
        "teamIds": [],
        "partnerInfos": [],
        "departmentId": "688897d5eb52b4af5573def4",
        "tutorialSettings": null,
        "miscellaneousSettings": null,
        "label": [],
        "userType": 0,
        "latestAnnouncementClosed": null,
        "contactId": null,
        "accountId": null,
        "recentData": null,
        "upcomingChangeStateIds": null,
        "source": "member",
        "isSso": null,
        "provider": null,
        "currentTeam": null,
        "currentPartner": null,
        "externalId": null,
        "externalEmployeeId": null,
        "externalIds": null,
        "department": null,
        "employeeStatus": null,
        "consumerType": 1,
        "thirdPartyIds": null,
        "version": 0,
        "createdAt": "2022-08-03T05:03:14.591Z",
        "updatedAt": "2022-08-03T05:03:14.591Z",
        "createdBy": null,
        "updatedBy": null,
        "isDeleted": false,
        "id": "62ea0192d27a0fab6f916f0a"
      },
      "plans": null,
      "teams": null,
      "partner": null,
      "consumerTeamConfigs": [],
      "emailConfirmed": true,
      "stripeCustomerId": "632c1265f4705941c0bc1bf7",
      "subscription": {
        "name": null,
        "planId": null,
        "stripeProductId": null,
        "productType": 11,
        "accountType": 2,
        "quantity": 1,
        "startDate": "2022-10-25T03:47:03Z",
        "endDate": "2022-11-24T03:47:03Z",
        "contractStartDate": null,
        "contractEndDate": null,
        "isTrial": true,
        "isCanceled": true,
        "isPaymentLate": false,
        "cancelAtPeriodEnd": false,
        "canceledBy": null,
        "canceledDate": null,
        "cancellationReason": 0,
        "stripeCouponId": null,
        "percentOff": null,
        "amountOff": null
      }
    },
    {
      "consumerObjectId": "630b5b08a7716ce2a4bc151e",
      "planObjectId": null,
      "teamObjectId": null,
      "consumers": {
        "firstName": "Claura",
        "normalizedFirstName": "CLAURA",
        "lastName": "Link",
        "normalizedLastName": "LINK",
        "fullName": "Claura Link",
        "normalizedFullName": "CLAURA LINK",
        "email": "viwuddauniyi-2839@yopmail.com",
        "normalizedEmail": "VIWUDDAUNIYI-2839@YOPMAIL.COM",
        "jobTitle": "QC",
        "companyName": "Bigin",
        "companySize": "1-99",
        "profilePicture": null,
        "phoneNumber": "",
        "address": null,
        "country": null,
        "state": null,
        "announcementStates": [
          {
            "teamId": null,
            "states": []
          }
        ],
        "timeZone": null,
        "dateOfBirth": null,
        "isActive": true,
        "lastActive": "0001-01-01T00:00:00Z",
        "casesFriendlyIdCounter": "00001",
        "exampleFriendlyId": null,
        "totalIndividualCases": 0,
        "teamIds": [],
        "partnerInfos": [],
        "departmentId": "688897d5eb52b4af5573def4",
        "tutorialSettings": null,
        "miscellaneousSettings": null,
        "label": [],
        "userType": 0,
        "latestAnnouncementClosed": null,
        "contactId": null,
        "accountId": null,
        "recentData": null,
        "upcomingChangeStateIds": null,
        "source": "member",
        "isSso": null,
        "provider": null,
        "currentTeam": null,
        "currentPartner": null,
        "externalId": null,
        "externalEmployeeId": null,
        "externalIds": null,
        "department": null,
        "employeeStatus": null,
        "consumerType": 1,
        "thirdPartyIds": null,
        "version": 0,
        "createdAt": "2022-08-28T12:09:44.311Z",
        "updatedAt": "2022-08-28T12:09:44.311Z",
        "createdBy": null,
        "updatedBy": null,
        "isDeleted": false,
        "id": "630b5b08a7716ce2a4bc151e"
      },
      "plans": null,
      "teams": null,
      "partner": null,
      "consumerTeamConfigs": [],
      "emailConfirmed": false,
      "stripeCustomerId": "632c126af4705941c0bc1bfd",
      "subscription": {
        "name": null,
        "planId": null,
        "stripeProductId": null,
        "productType": 11,
        "accountType": 2,
        "quantity": 1,
        "startDate": "2022-10-25T03:47:11Z",
        "endDate": "2022-11-24T03:47:11Z",
        "contractStartDate": null,
        "contractEndDate": null,
        "isTrial": true,
        "isCanceled": true,
        "isPaymentLate": false,
        "cancelAtPeriodEnd": false,
        "canceledBy": null,
        "canceledDate": null,
        "cancellationReason": 0,
        "stripeCouponId": null,
        "percentOff": null,
        "amountOff": null
      }
    },
    {
      "consumerObjectId": "630c8fafb54ef540a4e0e164",
      "planObjectId": null,
      "teamObjectId": null,
      "consumers": {
        "firstName": "An",
        "normalizedFirstName": "AN",
        "lastName": "Pham",
        "normalizedLastName": "PHAM",
        "fullName": "An Pham",
        "normalizedFullName": "AN PHAM",
        "email": "avpham@protonmail.com",
        "normalizedEmail": "AVPHAM@PROTONMAIL.COM",
        "jobTitle": "asd",
        "companyName": "asd",
        "companySize": "1-99",
        "profilePicture": null,
        "phoneNumber": null,
        "address": null,
        "country": null,
        "state": null,
        "announcementStates": [
          {
            "teamId": null,
            "states": []
          }
        ],
        "timeZone": null,
        "dateOfBirth": null,
        "isActive": true,
        "lastActive": "0001-01-01T00:00:00Z",
        "casesFriendlyIdCounter": "00001",
        "exampleFriendlyId": null,
        "totalIndividualCases": 0,
        "teamIds": [],
        "partnerInfos": [],
        "departmentId": "688897d5eb52b4af5573def4",
        "tutorialSettings": null,
        "miscellaneousSettings": null,
        "label": [],
        "userType": 0,
        "latestAnnouncementClosed": null,
        "contactId": null,
        "accountId": null,
        "recentData": null,
        "upcomingChangeStateIds": null,
        "source": "member",
        "isSso": null,
        "provider": null,
        "currentTeam": null,
        "currentPartner": null,
        "externalId": null,
        "externalEmployeeId": null,
        "externalIds": null,
        "department": null,
        "employeeStatus": null,
        "consumerType": 1,
        "thirdPartyIds": null,
        "version": 0,
        "createdAt": "2022-08-29T10:06:39.758Z",
        "updatedAt": "2022-08-29T10:06:39.758Z",
        "createdBy": null,
        "updatedBy": null,
        "isDeleted": false,
        "id": "630c8fafb54ef540a4e0e164"
      },
      "plans": null,
      "teams": null,
      "partner": null,
      "consumerTeamConfigs": [],
      "emailConfirmed": false,
      "stripeCustomerId": "632c1276f4705941c0bc1c0a",
      "subscription": {
        "name": null,
        "planId": null,
        "stripeProductId": null,
        "productType": 11,
        "accountType": 2,
        "quantity": 1,
        "startDate": "2022-10-25T03:47:27Z",
        "endDate": "2022-11-24T03:47:27Z",
        "contractStartDate": null,
        "contractEndDate": null,
        "isTrial": true,
        "isCanceled": true,
        "isPaymentLate": false,
        "cancelAtPeriodEnd": false,
        "canceledBy": null,
        "canceledDate": null,
        "cancellationReason": 0,
        "stripeCouponId": null,
        "percentOff": null,
        "amountOff": null
      }
    },
    {
      "consumerObjectId": "632029cb6513d65b424b0735",
      "planObjectId": null,
      "teamObjectId": null,
      "consumers": {
        "firstName": "Chuong",
        "normalizedFirstName": "CHUONG",
        "lastName": "Quan",
        "normalizedLastName": "QUAN",
        "fullName": "Chuong Quan",
        "normalizedFullName": "CHUONG QUAN",
        "email": "chuongquan13@gmail.com",
        "normalizedEmail": "CHUONGQUAN13@GMAIL.COM",
        "jobTitle": "Developer",
        "companyName": "Bigin",
        "companySize": "1-99",
        "profilePicture": null,
        "phoneNumber": null,
        "address": null,
        "country": null,
        "state": null,
        "announcementStates": [
          {
            "teamId": null,
            "states": []
          }
        ],
        "timeZone": null,
        "dateOfBirth": null,
        "isActive": true,
        "lastActive": "0001-01-01T00:00:00Z",
        "casesFriendlyIdCounter": "00001",
        "exampleFriendlyId": null,
        "totalIndividualCases": 0,
        "teamIds": [],
        "partnerInfos": [],
        "departmentId": "688897d5eb52b4af5573def4",
        "tutorialSettings": null,
        "miscellaneousSettings": null,
        "label": [],
        "userType": 0,
        "latestAnnouncementClosed": null,
        "contactId": null,
        "accountId": null,
        "recentData": null,
        "upcomingChangeStateIds": null,
        "source": "member",
        "isSso": null,
        "provider": null,
        "currentTeam": null,
        "currentPartner": null,
        "externalId": null,
        "externalEmployeeId": null,
        "externalIds": null,
        "department": null,
        "employeeStatus": null,
        "consumerType": 1,
        "thirdPartyIds": null,
        "version": 0,
        "createdAt": "2022-09-13T06:57:15.106Z",
        "updatedAt": "2022-09-13T06:57:15.106Z",
        "createdBy": null,
        "updatedBy": null,
        "isDeleted": false,
        "id": "632029cb6513d65b424b0735"
      },
      "plans": null,
      "teams": null,
      "partner": null,
      "consumerTeamConfigs": [],
      "emailConfirmed": false,
      "stripeCustomerId": "632c1291f4705941c0bc1c2b",
      "subscription": {
        "name": null,
        "planId": null,
        "stripeProductId": null,
        "productType": 11,
        "accountType": 2,
        "quantity": 1,
        "startDate": "2022-10-25T03:48:11Z",
        "endDate": "2022-11-24T03:48:11Z",
        "contractStartDate": null,
        "contractEndDate": null,
        "isTrial": true,
        "isCanceled": true,
        "isPaymentLate": false,
        "cancelAtPeriodEnd": false,
        "canceledBy": null,
        "canceledDate": null,
        "cancellationReason": 0,
        "stripeCouponId": null,
        "percentOff": null,
        "amountOff": null
      }
    },
    {
      "consumerObjectId": "632b07e6c17fb88820742e40",
      "planObjectId": null,
      "teamObjectId": null,
      "consumers": {
        "firstName": "duy",
        "normalizedFirstName": "DUY",
        "lastName": "test01",
        "normalizedLastName": "TEST01",
        "fullName": "duy test01",
        "normalizedFullName": "DUY TEST01",
        "email": "duytest01@yopmail.com",
        "normalizedEmail": "DUYTEST01@YOPMAIL.COM",
        "jobTitle": "dev",
        "companyName": "bigin",
        "companySize": "1-99",
        "profilePicture": null,
        "phoneNumber": null,
        "address": null,
        "country": null,
        "state": null,
        "announcementStates": [
          {
            "teamId": null,
            "states": []
          }
        ],
        "timeZone": null,
        "dateOfBirth": null,
        "isActive": true,
        "lastActive": "0001-01-01T00:00:00Z",
        "casesFriendlyIdCounter": "00001",
        "exampleFriendlyId": null,
        "totalIndividualCases": 0,
        "teamIds": [],
        "partnerInfos": [],
        "departmentId": "688897d5eb52b4af5573def4",
        "tutorialSettings": null,
        "miscellaneousSettings": null,
        "label": [],
        "userType": 0,
        "latestAnnouncementClosed": null,
        "contactId": null,
        "accountId": null,
        "recentData": null,
        "upcomingChangeStateIds": null,
        "source": "member",
        "isSso": null,
        "provider": null,
        "currentTeam": null,
        "currentPartner": null,
        "externalId": null,
        "externalEmployeeId": null,
        "externalIds": null,
        "department": null,
        "employeeStatus": null,
        "consumerType": 1,
        "thirdPartyIds": null,
        "version": 0,
        "createdAt": "2022-09-21T12:47:34.675Z",
        "updatedAt": "2022-09-21T12:47:34.674Z",
        "createdBy": null,
        "updatedBy": null,
        "isDeleted": false,
        "id": "632b07e6c17fb88820742e40"
      },
      "plans": null,
      "teams": null,
      "partner": null,
      "consumerTeamConfigs": [],
      "emailConfirmed": false,
      "stripeCustomerId": null,
      "subscription": null
    }
  ]
}