{
    "plans": [
        {
            "name": "500+ Employees & HR Consultants2",
            "productType": 6,
            "licenseQuantity": 0,
            "isActive": true,
            "price": {
                "id": "price_1T418hBhKjoN79ja8kPVZ5au",
                "unitAmountInCents": 0.0,
                "unitAmount": 0.0,
                "type": "recurring",
                "productType": 0,
                "recurring": {
                    "interval": "year",
                    "intervalCount": 1
                },
                "currency": "usd"
            },
            "version": 34,
            "createdAt": "2026-02-23T15:33:39.865Z",
            "updatedAt": "2026-02-23T15:33:39.865Z",
            "createdBy": null,
            "updatedBy": null,
            "isDeleted": false,
            "id": "699c735434165dad7f84f5f8"
        }
    ],
    "partners": [],
    "teams": [
        {
            "name": "Individual 01",
            "normalizedName": "INDIVIDUAL 01",
            "code": "Individual 01-XD8S98",
            "contactEmail": null,
            "contactPhone": null,
            "invoiceEmail": null,
            "profilePicture": null,
            "coverPhoto": null,
            "members": [],
            "partnerId": null,
            "subDomain": null,
            "departmentId": "688897d5eb52b4af5573def4",
            "source": "virgilhr",
            "isActive": true,
            "casesFriendlyIdCounter": "00001",
            "totalCases": 0,
            "label": [],
            "createHistoryTaskBaseOnAnnouncements": true,
            "backUrl": null,
            "backText": null,
            "assignedIds": [],
            "externalCompanyId": null,
            "version": 0,
            "createdAt": "2026-02-23T15:33:45.257Z",
            "updatedAt": "2026-02-23T15:33:45.257Z",
            "createdBy": null,
            "updatedBy": null,
            "isDeleted": false,
            "id": "699c735934165dad7f84f5fc"
        }
    ],
    "total": 1,
    "entities": [
        {
            "consumerObjectId": "699c635c34165dad7f84f5f0",
            "planObjectId": "699c735434165dad7f84f5f8",
            "teamObjectId": null,
            "consumers": {
                "firstName": "Individual",
                "normalizedFirstName": "INDIVIDUAL",
                "lastName": "01",
                "normalizedLastName": "01",
                "fullName": "Individual 01",
                "normalizedFullName": "INDIVIDUAL 01",
                "email": "Individual01@yopmail.com",
                "normalizedEmail": "INDIVIDUAL01@YOPMAIL.COM",
                "jobTitle": "Test",
                "companyName": "Individual 01",
                "companySize": "500+",
                "profilePicture": null,
                "phoneNumber": "234234234234",
                "address": null,
                "country": {
                    "key": "US",
                    "value": "United States"
                },
                "state": null,
                "announcementStates": [
                    {
                        "teamId": "699c735934165dad7f84f5fc",
                        "states": []
                    }
                ],
                "timeZone": null,
                "dateOfBirth": null,
                "isActive": true,
                "lastActive": "2026-02-23T16:32:52.14Z",
                "casesFriendlyIdCounter": "00001",
                "exampleFriendlyId": null,
                "totalIndividualCases": 0,
                "teamIds": [
                    "699c735934165dad7f84f5fc"
                ],
                "partnerInfos": [],
                "departmentId": "688897d5eb52b4af5573def4",
                "tutorialSettings": null,
                "miscellaneousSettings": null,
                "label": [],
                "userType": 1,
                "latestAnnouncementClosed": null,
                "contactId": null,
                "accountId": null,
                "recentData": null,
                "upcomingChangeStateIds": null,
                "source": "virgilhr",
                "isSso": false,
                "provider": null,
                "currentTeam": "699c735934165dad7f84f5fc",
                "currentPartner": null,
                "externalId": null,
                "externalEmployeeId": null,
                "externalIds": null,
                "department": null,
                "employeeStatus": null,
                "consumerType": 1,
                "thirdPartyIds": null,
                "version": 0,
                "createdAt": "2026-02-23T14:25:32.383Z",
                "updatedAt": "2026-02-23T14:25:32.383Z",
                "createdBy": null,
                "updatedBy": null,
                "isDeleted": false,
                "id": "699c635c34165dad7f84f5f0"
            },
            "plans": null,
            "teams": null,
            "partner": null,
            "consumerTeamConfigs": [],
            "emailConfirmed": true,
            "stripeCustomerId": "699c635d34165dad7f84f5f1",
            "subscription": {
                "name": "500+ Employees & HR Consultants2",
                "planId": "699c735434165dad7f84f5f8",
                "stripeProductId": "prod_NLfIuzyP4FlJEo",
                "productType": 6,
                "accountType": 3,
                "quantity": 1,
                "startDate": "2026-02-23T15:33:40Z",
                "endDate": "2027-02-23T15:33:40Z",
                "contractStartDate": "2026-02-23T15:33:40Z",
                "contractEndDate": "2027-02-23T15:33:40Z",
                "isTrial": false,
                "isCanceled": false,
                "isPaymentLate": false,
                "cancelAtPeriodEnd": false,
                "canceledBy": null,
                "canceledDate": null,
                "cancellationReason": 0,
                "stripeCouponId": null,
                "percentOff": null,
                "amountOff": null
            }
        }
    ]
}