# init.ps1 — Initialise qa-artifacts workspace (Windows / PowerShell)
# Run from the project root: .\scripts\init.ps1
# Safe to re-run — existing files are never overwritten.

param(
  [switch]$Reset   # Pass -Reset to delete and recreate qa-artifacts/
)

$base = $PSScriptRoot | Split-Path   # project root (one level above scripts/)

# ── Optionally reset ────────────────────────────────────────────────────────
if ($Reset -and (Test-Path "$base\qa-artifacts")) {
  Remove-Item -Recurse -Force "$base\qa-artifacts"
  Write-Host "qa-artifacts/ removed."
}

# ── Folder list ─────────────────────────────────────────────────────────────
$folders = @(
  "requirements",
  "qa-artifacts\0-sprint-tickets",
  "qa-artifacts\1-requirements-analysis",
  "qa-artifacts\2-test-plan",
  "qa-artifacts\3-test-cases",
  "qa-artifacts\4-execution-results",
  "qa-artifacts\4-execution-results\screenshots",
  "qa-artifacts\5-testing-report",
  "qa-artifacts\base-test"
)

foreach ($f in $folders) {
  $path = Join-Path $base $f
  if (-not (Test-Path $path)) {
    New-Item -ItemType Directory -Path $path -Force | Out-Null
    Write-Host "  Created : $f"
  } else {
    Write-Host "  Exists  : $f"
  }
}

# ── README files ─────────────────────────────────────────────────────────────
$readmes = @{
  "qa-artifacts\0-sprint-tickets\README.md" = @"
# 0 — Sprint Tickets

**Generated by:** op-fetch-sprint-tickets
**Output files:** sprint<N>-tickets.md (one file per sprint fetched)

Each file contains the full ticket list for a sprint, grouped by status.
"@

  "requirements\README.md" = @"
# requirements/

Place your requirement `.md` files here before starting the STLC pipeline.

Each file should describe one or more features using:
- User stories ("As a ... I want ... so that ...")
- Acceptance criteria (numbered list or Given/When/Then)
- Out-of-scope statements (optional but recommended)

**Next step:** Run the ``stlc-requirements-analyst`` skill.
"@

  "qa-artifacts\1-requirements-analysis\README.md" = @"
# 1 — Requirements Analysis

**Generated by:** stlc-requirements-analyst
**Output file:** requirements-analysis.md
"@

  "qa-artifacts\2-test-plan\README.md" = @"
# 2 — Test Plan

**Generated by:** stlc-test-plan-designer
**Output file:** test-plan.md
"@

  "qa-artifacts\3-test-cases\README.md" = @"
# 3 — Test Cases

**Generated by:** stlc-testcase-designer
**Output file:** test-cases.md
"@

  "qa-artifacts\4-execution-results\README.md" = @"
# 4 — Execution Results

**Generated by:** stlc-manual-executor
**Output files:** execution-log.md · screenshots/
"@

  "qa-artifacts\4-execution-results\screenshots\README.md" = @"
# screenshots/

Browser screenshots captured during test execution.
Naming: TC-XXX-[pass|fail]-stepN.png
"@

  "qa-artifacts\5-testing-report\README.md" = @"
# 5 — Testing Report

**Generated by:** stlc-bug-reporter + stlc-test-reporter
**Output files:** bug-report.md · test-report.md
"@
}

foreach ($entry in $readmes.GetEnumerator()) {
  $path = Join-Path $base $entry.Key
  if (-not (Test-Path $path)) {
    Set-Content -Path $path -Value $entry.Value -Encoding UTF8
    Write-Host "  README  : $($entry.Key)"
  }
}

# ── test-centralized.md ──────────────────────────────────────────────────────
$testCentralized = Join-Path $base "qa-artifacts\base-test\test-centralized.md"
if (-not (Test-Path $testCentralized)) {
  Set-Content -Path $testCentralized -Encoding UTF8 -Value @"
# Centralized Test Accounts

> **Tier** column applies to Customer and Authorized roles only. Use ``—`` for Admin-side roles.
> **Member portal** = consumer-facing app. **Admin portal** = back-office management.

---

## QA Environment

| Env | Portal | Role | Email | Password | Tier |
|---|---|---|---|---|---|
| QA | Admin | Super Admin | ``duy.duong@bigin.vn`` | ``12345689`` | — |
| QA | Admin | Admin | ``vinh.admin@yopmail.com`` | ``Password@123`` | — |
| QA | Admin | Staff | ``vinh.le.staff@yopmail.com`` | ``Password@123`` | — |
| QA | Member | Customer | ``vinh.uat.customer2@yopmail.com`` | ``Password@123`` | Freemium |
| QA | Member | Customer | ``bam@drommond.com`` | ``Password@123`` | Platinum |
| QA | Member | Customer | ``masjroberts7@gmail.com`` | ``DrivingHope@2026`` | Knight |
| QA | Member | Authorized | ``vinh.authorized.01@yopmail.com`` | ``Password@123`` | Freemium |
| UAT | Admin | Super Admin | ``duy.duong@bigin.vn`` | ``12345689`` | — |
| UAT | Admin | Admin | ``vinh.admin3@yopmail.com`` | ``Password@123`` | — |
| UAT | Admin | Staff | _(not configured)_ | — | — |
| UAT | Member | Customer | ``vinh.uat.customer2@yopmail.com`` | ``Password@123`` | Freemium |
| UAT | Member | Customer | ``bam@drommond.com`` | ``Password@123`` | Platinum |
| UAT | Member | Customer | ``masjroberts7@gmail.com`` | ``DrivingHope@2026`` | Knight |
| UAT | Member | Authorized | ``vinh.authorized.01@yopmail.com`` | ``Password@123`` | Freemium |
"@
  Write-Host "  Created : qa-artifacts\base-test\test-centralized.md"
} else {
  Write-Host "  Exists  : qa-artifacts\base-test\test-centralized.md"
}

# ── .env bootstrap ──────────────────────────────────────────────────────────
$envFile     = Join-Path $base ".env"
$envExample  = Join-Path $base ".env.example"
if (-not (Test-Path $envFile) -and (Test-Path $envExample)) {
  Copy-Item $envExample $envFile
  Write-Host ""
  Write-Host "  .env created from .env.example."
  Write-Host "  Fill in APP_BASE_URL and tracker credentials before running the pipeline."
}

# ── Summary ──────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "Workspace ready. Add requirement .md files to requirements/ then run stlc-requirements-analyst."
