#!/usr/bin/env bash
# init.sh — Initialise qa-artifacts workspace (macOS / Linux)
# Run from the project root: bash .cursor/skills/stlc-init-workspace/scripts/init.sh
# Safe to re-run — existing files are never overwritten.
# Pass --reset to delete and recreate qa-artifacts/

set -euo pipefail

BASE="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../.." && pwd)"   # project root
RESET=false
[[ "${1:-}" == "--reset" ]] && RESET=true

# ── Optionally reset ─────────────────────────────────────────────────────────
if $RESET && [ -d "$BASE/qa-artifacts" ]; then
  rm -rf "$BASE/qa-artifacts"
  echo "  qa-artifacts/ removed."
fi

# ── Folders ──────────────────────────────────────────────────────────────────
FOLDERS=(
  "requirements"
  "qa-artifacts/0-sprint-tickets"
  "qa-artifacts/1-requirements-analysis"
  "qa-artifacts/2-test-plan"
  "qa-artifacts/3-test-cases"
  "qa-artifacts/4-execution-results"
  "qa-artifacts/4-execution-results/screenshots"
  "qa-artifacts/5-testing-report"
  "qa-artifacts/base-test"
)

for f in "${FOLDERS[@]}"; do
  target="$BASE/$f"
  if [ ! -d "$target" ]; then
    mkdir -p "$target"
    echo "  Created : $f"
  else
    echo "  Exists  : $f"
  fi
done

# ── README files ─────────────────────────────────────────────────────────────
write_readme() {
  local path="$BASE/$1"
  local content="$2"
  if [ ! -f "$path" ]; then
    echo "$content" > "$path"
    echo "  README  : $1"
  fi
}

write_readme "qa-artifacts/0-sprint-tickets/README.md" \
"# 0 — Sprint Tickets
Generated by: op-fetch-sprint-tickets
Output files: sprint<N>-tickets.md (one file per sprint fetched)

Each file contains the full ticket list for a sprint, grouped by status."

write_readme "requirements/README.md" \
"# requirements/

Place your requirement \`.md\` files here before starting the STLC pipeline.

Each file should describe features using user stories, acceptance criteria, and out-of-scope statements.

**Next step:** Run the \`stlc-requirements-analyst\` skill."

write_readme "qa-artifacts/1-requirements-analysis/README.md" \
"# 1 — Requirements Analysis
Generated by: stlc-requirements-analyst
Output file:  requirements-analysis.md"

write_readme "qa-artifacts/2-test-plan/README.md" \
"# 2 — Test Plan
Generated by: stlc-test-plan-designer
Output file:  test-plan.md"

write_readme "qa-artifacts/3-test-cases/README.md" \
"# 3 — Test Cases
Generated by: stlc-testcase-designer
Output file:  test-cases.md"

write_readme "qa-artifacts/4-execution-results/README.md" \
"# 4 — Execution Results
Generated by: stlc-manual-executor
Output files: execution-log.md · screenshots/"

write_readme "qa-artifacts/4-execution-results/screenshots/README.md" \
"# screenshots/
Browser screenshots captured during test execution.
Naming: TC-XXX-[pass|fail]-stepN.png"

write_readme "qa-artifacts/5-testing-report/README.md" \
"# 5 — Testing Report
Generated by: stlc-bug-reporter + stlc-test-reporter
Output files: bug-report.md · test-report.md"

# ── test-centralized.md ──────────────────────────────────────────────────────
TEST_CENTRALIZED="$BASE/qa-artifacts/base-test/test-centralized.md"
if [ ! -f "$TEST_CENTRALIZED" ]; then
  cat > "$TEST_CENTRALIZED" << 'EOF'
# Centralized Test Accounts

> **Tier** column applies to Customer and Authorized roles only. Use `—` for Admin-side roles.
> **Member portal** = consumer-facing app. **Admin portal** = back-office management.

---

## QA Environment

| Env | Portal | Role | Email | Password | Tier |
|---|---|---|---|---|---|
| QA | Admin | Super Admin | `duy.duong@bigin.vn` | `12345689` | — |
| QA | Admin | Admin | `vinh.admin@yopmail.com` | `Password@123` | — |
| QA | Admin | Staff | `vinh.le.staff@yopmail.com` | `Password@123` | — |
| QA | Member | Customer | `vinh.uat.customer2@yopmail.com` | `Password@123` | Freemium |
| QA | Member | Customer | `bam@drommond.com` | `Password@123` | Platinum |
| QA | Member | Customer | `masjroberts7@gmail.com` | `DrivingHope@2026` | Knight |
| QA | Member | Authorized | `vinh.authorized.01@yopmail.com` | `Password@123` | Freemium |
| UAT | Admin | Super Admin | `duy.duong@bigin.vn` | `12345689` | — |
| UAT | Admin | Admin | `vinh.admin3@yopmail.com` | `Password@123` | — |
| UAT | Admin | Staff | _(not configured)_ | — | — |
| UAT | Member | Customer | `vinh.uat.customer2@yopmail.com` | `Password@123` | Freemium |
| UAT | Member | Customer | `bam@drommond.com` | `Password@123` | Platinum |
| UAT | Member | Customer | `masjroberts7@gmail.com` | `DrivingHope@2026` | Knight |
| UAT | Member | Authorized | `vinh.authorized.01@yopmail.com` | `Password@123` | Freemium |
EOF
  echo "  Created : qa-artifacts/base-test/test-centralized.md"
else
  echo "  Exists  : qa-artifacts/base-test/test-centralized.md"
fi

# ── .env bootstrap ───────────────────────────────────────────────────────────
if [ ! -f "$BASE/.env" ] && [ -f "$BASE/.env.example" ]; then
  cp "$BASE/.env.example" "$BASE/.env"
  echo ""
  echo "  .env created from .env.example."
  echo "  Fill in APP_BASE_URL and tracker credentials before running the pipeline."
fi

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo "Workspace ready. Add requirement .md files to requirements/ then run stlc-requirements-analyst."
